# Generated by Django 4.2.4 on 2023-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0003_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='capa',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ManyToManyField(blank=True, default=None, related_name='+', to='uploader.image'),
        ),
    ]
