# Generated by Django 4.2.4 on 2023-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_remove_veiculo_categoria_remove_veiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
