# Generated by Django 4.1.7 on 2023-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_modelo_alter_acessorio_options_alter_cor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(related_name='veiculos', to='garagem.acessorio'),
        ),
    ]
