# Generated by Django 4.2.4 on 2023-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_alter_acessorio_id_alter_cor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
