# Generated by Django 4.2.4 on 2023-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0007_rename_descricao_modelo_nome_veiculo_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
