# Generated by Django 4.2.4 on 2023-08-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0008_remove_veiculo_descricao_alter_veiculo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
